# coding: utf-8

"""
    Requisition

    Here's our story,  It all began with the frustration of using software that sucks. Prior to starting Keka, our core team was a 100 person business that needed an easy to use software for managing employees. We looked everywhere and all we found were software that was lousy and hard to use. We felt SME businesses in India deserved something better. Something awesome actually!  Thus emerged Keka!

    The version of the OpenAPI document: v1
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from keka_hr_python_sdk import schemas  # noqa: F401


class Employee(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        required = {
            "firstName",
            "lastName",
            "businessUnit",
            "gender",
            "displayName",
            "dateJoined",
            "jobTitle",
            "dateOfBirth",
            "location",
            "department",
            "email",
        }
        
        class properties:
            displayName = schemas.StrSchema
            firstName = schemas.StrSchema
            lastName = schemas.StrSchema
            email = schemas.StrSchema
        
            @staticmethod
            def gender() -> typing.Type['Gender']:
                return Gender
            dateOfBirth = schemas.DateTimeSchema
            dateJoined = schemas.DateTimeSchema
            department = schemas.StrSchema
            businessUnit = schemas.StrSchema
            jobTitle = schemas.StrSchema
            location = schemas.StrSchema
            
            
            class employeeNumber(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                def __new__(
                    cls,
                    *args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'employeeNumber':
                    return super().__new__(
                        cls,
                        *args,
                        _configuration=_configuration,
                    )
            
            
            class middleName(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                def __new__(
                    cls,
                    *args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'middleName':
                    return super().__new__(
                        cls,
                        *args,
                        _configuration=_configuration,
                    )
            
            
            class mobileNumber(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                class MetaOapg:
                    format = 'tel'
            
            
                def __new__(
                    cls,
                    *args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'mobileNumber':
                    return super().__new__(
                        cls,
                        *args,
                        _configuration=_configuration,
                    )
            
            
            class secondaryJobTitle(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                def __new__(
                    cls,
                    *args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'secondaryJobTitle':
                    return super().__new__(
                        cls,
                        *args,
                        _configuration=_configuration,
                    )
            __annotations__ = {
                "displayName": displayName,
                "firstName": firstName,
                "lastName": lastName,
                "email": email,
                "gender": gender,
                "dateOfBirth": dateOfBirth,
                "dateJoined": dateJoined,
                "department": department,
                "businessUnit": businessUnit,
                "jobTitle": jobTitle,
                "location": location,
                "employeeNumber": employeeNumber,
                "middleName": middleName,
                "mobileNumber": mobileNumber,
                "secondaryJobTitle": secondaryJobTitle,
            }
    
    firstName: MetaOapg.properties.firstName
    lastName: MetaOapg.properties.lastName
    businessUnit: MetaOapg.properties.businessUnit
    gender: 'Gender'
    displayName: MetaOapg.properties.displayName
    dateJoined: MetaOapg.properties.dateJoined
    jobTitle: MetaOapg.properties.jobTitle
    dateOfBirth: MetaOapg.properties.dateOfBirth
    location: MetaOapg.properties.location
    department: MetaOapg.properties.department
    email: MetaOapg.properties.email
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["displayName"]) -> MetaOapg.properties.displayName: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["firstName"]) -> MetaOapg.properties.firstName: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["lastName"]) -> MetaOapg.properties.lastName: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["email"]) -> MetaOapg.properties.email: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["gender"]) -> 'Gender': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["dateOfBirth"]) -> MetaOapg.properties.dateOfBirth: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["dateJoined"]) -> MetaOapg.properties.dateJoined: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["department"]) -> MetaOapg.properties.department: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["businessUnit"]) -> MetaOapg.properties.businessUnit: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["jobTitle"]) -> MetaOapg.properties.jobTitle: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["location"]) -> MetaOapg.properties.location: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["employeeNumber"]) -> MetaOapg.properties.employeeNumber: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["middleName"]) -> MetaOapg.properties.middleName: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["mobileNumber"]) -> MetaOapg.properties.mobileNumber: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["secondaryJobTitle"]) -> MetaOapg.properties.secondaryJobTitle: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["displayName", "firstName", "lastName", "email", "gender", "dateOfBirth", "dateJoined", "department", "businessUnit", "jobTitle", "location", "employeeNumber", "middleName", "mobileNumber", "secondaryJobTitle", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["displayName"]) -> MetaOapg.properties.displayName: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["firstName"]) -> MetaOapg.properties.firstName: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["lastName"]) -> MetaOapg.properties.lastName: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["email"]) -> MetaOapg.properties.email: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["gender"]) -> 'Gender': ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["dateOfBirth"]) -> MetaOapg.properties.dateOfBirth: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["dateJoined"]) -> MetaOapg.properties.dateJoined: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["department"]) -> MetaOapg.properties.department: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["businessUnit"]) -> MetaOapg.properties.businessUnit: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["jobTitle"]) -> MetaOapg.properties.jobTitle: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["location"]) -> MetaOapg.properties.location: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["employeeNumber"]) -> typing.Union[MetaOapg.properties.employeeNumber, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["middleName"]) -> typing.Union[MetaOapg.properties.middleName, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["mobileNumber"]) -> typing.Union[MetaOapg.properties.mobileNumber, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["secondaryJobTitle"]) -> typing.Union[MetaOapg.properties.secondaryJobTitle, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["displayName", "firstName", "lastName", "email", "gender", "dateOfBirth", "dateJoined", "department", "businessUnit", "jobTitle", "location", "employeeNumber", "middleName", "mobileNumber", "secondaryJobTitle", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        firstName: typing.Union[MetaOapg.properties.firstName, str, ],
        lastName: typing.Union[MetaOapg.properties.lastName, str, ],
        businessUnit: typing.Union[MetaOapg.properties.businessUnit, str, ],
        gender: 'Gender',
        displayName: typing.Union[MetaOapg.properties.displayName, str, ],
        dateJoined: typing.Union[MetaOapg.properties.dateJoined, str, datetime, ],
        jobTitle: typing.Union[MetaOapg.properties.jobTitle, str, ],
        dateOfBirth: typing.Union[MetaOapg.properties.dateOfBirth, str, datetime, ],
        location: typing.Union[MetaOapg.properties.location, str, ],
        department: typing.Union[MetaOapg.properties.department, str, ],
        email: typing.Union[MetaOapg.properties.email, str, ],
        employeeNumber: typing.Union[MetaOapg.properties.employeeNumber, None, str, schemas.Unset] = schemas.unset,
        middleName: typing.Union[MetaOapg.properties.middleName, None, str, schemas.Unset] = schemas.unset,
        mobileNumber: typing.Union[MetaOapg.properties.mobileNumber, None, str, schemas.Unset] = schemas.unset,
        secondaryJobTitle: typing.Union[MetaOapg.properties.secondaryJobTitle, None, str, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'Employee':
        return super().__new__(
            cls,
            *args,
            firstName=firstName,
            lastName=lastName,
            businessUnit=businessUnit,
            gender=gender,
            displayName=displayName,
            dateJoined=dateJoined,
            jobTitle=jobTitle,
            dateOfBirth=dateOfBirth,
            location=location,
            department=department,
            email=email,
            employeeNumber=employeeNumber,
            middleName=middleName,
            mobileNumber=mobileNumber,
            secondaryJobTitle=secondaryJobTitle,
            _configuration=_configuration,
            **kwargs,
        )

from keka_hr_python_sdk.model.gender import Gender
