# coding: utf-8

"""
    Requisition

    Here's our story,  It all began with the frustration of using software that sucks. Prior to starting Keka, our core team was a 100 person business that needed an easy to use software for managing employees. We looked everywhere and all we found were software that was lousy and hard to use. We felt SME businesses in India deserved something better. Something awesome actually!  Thus emerged Keka!

    The version of the OpenAPI document: v1
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from keka_hr_python_sdk import schemas  # noqa: F401


class JobDetailsUpdateRequest(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        class properties:
            
            
            class employeeNumber(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                def __new__(
                    cls,
                    *args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'employeeNumber':
                    return super().__new__(
                        cls,
                        *args,
                        _configuration=_configuration,
                    )
            
            
            class location(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                def __new__(
                    cls,
                    *args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'location':
                    return super().__new__(
                        cls,
                        *args,
                        _configuration=_configuration,
                    )
            
            
            class businessUnit(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                def __new__(
                    cls,
                    *args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'businessUnit':
                    return super().__new__(
                        cls,
                        *args,
                        _configuration=_configuration,
                    )
            
            
            class department(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                def __new__(
                    cls,
                    *args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'department':
                    return super().__new__(
                        cls,
                        *args,
                        _configuration=_configuration,
                    )
            
            
            class jobTitle(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                def __new__(
                    cls,
                    *args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'jobTitle':
                    return super().__new__(
                        cls,
                        *args,
                        _configuration=_configuration,
                    )
            
            
            class reportingManager(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                def __new__(
                    cls,
                    *args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'reportingManager':
                    return super().__new__(
                        cls,
                        *args,
                        _configuration=_configuration,
                    )
            
            
            class attendanceNumber(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                def __new__(
                    cls,
                    *args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'attendanceNumber':
                    return super().__new__(
                        cls,
                        *args,
                        _configuration=_configuration,
                    )
        
            @staticmethod
            def timeType() -> typing.Type['TimeType']:
                return TimeType
            
            
            class attendanceCaptureScheme(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                def __new__(
                    cls,
                    *args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'attendanceCaptureScheme':
                    return super().__new__(
                        cls,
                        *args,
                        _configuration=_configuration,
                    )
            
            
            class expensePolicy(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                def __new__(
                    cls,
                    *args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'expensePolicy':
                    return super().__new__(
                        cls,
                        *args,
                        _configuration=_configuration,
                    )
            
            
            class noticePeriod(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                def __new__(
                    cls,
                    *args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'noticePeriod':
                    return super().__new__(
                        cls,
                        *args,
                        _configuration=_configuration,
                    )
            
            
            class holidayList(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                def __new__(
                    cls,
                    *args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'holidayList':
                    return super().__new__(
                        cls,
                        *args,
                        _configuration=_configuration,
                    )
            
            
            class costCenter(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                def __new__(
                    cls,
                    *args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'costCenter':
                    return super().__new__(
                        cls,
                        *args,
                        _configuration=_configuration,
                    )
            
            
            class payBand(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                def __new__(
                    cls,
                    *args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'payBand':
                    return super().__new__(
                        cls,
                        *args,
                        _configuration=_configuration,
                    )
            
            
            class payGrade(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                def __new__(
                    cls,
                    *args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'payGrade':
                    return super().__new__(
                        cls,
                        *args,
                        _configuration=_configuration,
                    )
        
            @staticmethod
            def customFields() -> typing.Type['JobDetailsUpdateRequestCustomFields']:
                return JobDetailsUpdateRequestCustomFields
            __annotations__ = {
                "employeeNumber": employeeNumber,
                "location": location,
                "businessUnit": businessUnit,
                "department": department,
                "jobTitle": jobTitle,
                "reportingManager": reportingManager,
                "attendanceNumber": attendanceNumber,
                "timeType": timeType,
                "attendanceCaptureScheme": attendanceCaptureScheme,
                "expensePolicy": expensePolicy,
                "noticePeriod": noticePeriod,
                "holidayList": holidayList,
                "costCenter": costCenter,
                "payBand": payBand,
                "payGrade": payGrade,
                "customFields": customFields,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["employeeNumber"]) -> MetaOapg.properties.employeeNumber: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["location"]) -> MetaOapg.properties.location: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["businessUnit"]) -> MetaOapg.properties.businessUnit: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["department"]) -> MetaOapg.properties.department: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["jobTitle"]) -> MetaOapg.properties.jobTitle: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["reportingManager"]) -> MetaOapg.properties.reportingManager: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["attendanceNumber"]) -> MetaOapg.properties.attendanceNumber: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["timeType"]) -> 'TimeType': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["attendanceCaptureScheme"]) -> MetaOapg.properties.attendanceCaptureScheme: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["expensePolicy"]) -> MetaOapg.properties.expensePolicy: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["noticePeriod"]) -> MetaOapg.properties.noticePeriod: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["holidayList"]) -> MetaOapg.properties.holidayList: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["costCenter"]) -> MetaOapg.properties.costCenter: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["payBand"]) -> MetaOapg.properties.payBand: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["payGrade"]) -> MetaOapg.properties.payGrade: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["customFields"]) -> 'JobDetailsUpdateRequestCustomFields': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["employeeNumber", "location", "businessUnit", "department", "jobTitle", "reportingManager", "attendanceNumber", "timeType", "attendanceCaptureScheme", "expensePolicy", "noticePeriod", "holidayList", "costCenter", "payBand", "payGrade", "customFields", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["employeeNumber"]) -> typing.Union[MetaOapg.properties.employeeNumber, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["location"]) -> typing.Union[MetaOapg.properties.location, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["businessUnit"]) -> typing.Union[MetaOapg.properties.businessUnit, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["department"]) -> typing.Union[MetaOapg.properties.department, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["jobTitle"]) -> typing.Union[MetaOapg.properties.jobTitle, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["reportingManager"]) -> typing.Union[MetaOapg.properties.reportingManager, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["attendanceNumber"]) -> typing.Union[MetaOapg.properties.attendanceNumber, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["timeType"]) -> typing.Union['TimeType', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["attendanceCaptureScheme"]) -> typing.Union[MetaOapg.properties.attendanceCaptureScheme, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["expensePolicy"]) -> typing.Union[MetaOapg.properties.expensePolicy, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["noticePeriod"]) -> typing.Union[MetaOapg.properties.noticePeriod, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["holidayList"]) -> typing.Union[MetaOapg.properties.holidayList, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["costCenter"]) -> typing.Union[MetaOapg.properties.costCenter, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["payBand"]) -> typing.Union[MetaOapg.properties.payBand, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["payGrade"]) -> typing.Union[MetaOapg.properties.payGrade, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["customFields"]) -> typing.Union['JobDetailsUpdateRequestCustomFields', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["employeeNumber", "location", "businessUnit", "department", "jobTitle", "reportingManager", "attendanceNumber", "timeType", "attendanceCaptureScheme", "expensePolicy", "noticePeriod", "holidayList", "costCenter", "payBand", "payGrade", "customFields", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        employeeNumber: typing.Union[MetaOapg.properties.employeeNumber, None, str, schemas.Unset] = schemas.unset,
        location: typing.Union[MetaOapg.properties.location, None, str, schemas.Unset] = schemas.unset,
        businessUnit: typing.Union[MetaOapg.properties.businessUnit, None, str, schemas.Unset] = schemas.unset,
        department: typing.Union[MetaOapg.properties.department, None, str, schemas.Unset] = schemas.unset,
        jobTitle: typing.Union[MetaOapg.properties.jobTitle, None, str, schemas.Unset] = schemas.unset,
        reportingManager: typing.Union[MetaOapg.properties.reportingManager, None, str, schemas.Unset] = schemas.unset,
        attendanceNumber: typing.Union[MetaOapg.properties.attendanceNumber, None, str, schemas.Unset] = schemas.unset,
        timeType: typing.Union['TimeType', schemas.Unset] = schemas.unset,
        attendanceCaptureScheme: typing.Union[MetaOapg.properties.attendanceCaptureScheme, None, str, schemas.Unset] = schemas.unset,
        expensePolicy: typing.Union[MetaOapg.properties.expensePolicy, None, str, schemas.Unset] = schemas.unset,
        noticePeriod: typing.Union[MetaOapg.properties.noticePeriod, None, str, schemas.Unset] = schemas.unset,
        holidayList: typing.Union[MetaOapg.properties.holidayList, None, str, schemas.Unset] = schemas.unset,
        costCenter: typing.Union[MetaOapg.properties.costCenter, None, str, schemas.Unset] = schemas.unset,
        payBand: typing.Union[MetaOapg.properties.payBand, None, str, schemas.Unset] = schemas.unset,
        payGrade: typing.Union[MetaOapg.properties.payGrade, None, str, schemas.Unset] = schemas.unset,
        customFields: typing.Union['JobDetailsUpdateRequestCustomFields', schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'JobDetailsUpdateRequest':
        return super().__new__(
            cls,
            *args,
            employeeNumber=employeeNumber,
            location=location,
            businessUnit=businessUnit,
            department=department,
            jobTitle=jobTitle,
            reportingManager=reportingManager,
            attendanceNumber=attendanceNumber,
            timeType=timeType,
            attendanceCaptureScheme=attendanceCaptureScheme,
            expensePolicy=expensePolicy,
            noticePeriod=noticePeriod,
            holidayList=holidayList,
            costCenter=costCenter,
            payBand=payBand,
            payGrade=payGrade,
            customFields=customFields,
            _configuration=_configuration,
            **kwargs,
        )

from keka_hr_python_sdk.model.job_details_update_request_custom_fields import JobDetailsUpdateRequestCustomFields
from keka_hr_python_sdk.model.time_type import TimeType
