# coding: utf-8

"""
    Requisition

    Here's our story,  It all began with the frustration of using software that sucks. Prior to starting Keka, our core team was a 100 person business that needed an easy to use software for managing employees. We looked everywhere and all we found were software that was lousy and hard to use. We felt SME businesses in India deserved something better. Something awesome actually!  Thus emerged Keka!

    The version of the OpenAPI document: v1
    Generated by: https://konfigthis.com
"""

import unittest

import os
from pprint import pprint
from keka_hr_python_sdk import KekaHr

class TestSimple(unittest.TestCase):
    def setUp(self):
        pass

    def test_client(self):
        kekahr = KekaHr(
        
            client_id = 'YOUR_CLIENT_ID',
            client_secret = 'YOUR_CLIENT_SECRET',,
        
            client_id = 'YOUR_CLIENT_ID',
            client_secret = 'YOUR_CLIENT_SECRET',
        )
        self.assertIsNotNone(kekahr)

    def tearDown(self):
        pass


if __name__ == "__main__":
    unittest.main()
