# coding: utf-8

"""
    Requisition

    Here's our story,  It all began with the frustration of using software that sucks. Prior to starting Keka, our core team was a 100 person business that needed an easy to use software for managing employees. We looked everywhere and all we found were software that was lousy and hard to use. We felt SME businesses in India deserved something better. Something awesome actually!  Thus emerged Keka!

    The version of the OpenAPI document: v1
    Generated by: https://konfigthis.com
"""

import unittest
from unittest.mock import patch

import urllib3

import keka_hr_python_sdk
from keka_hr_python_sdk.paths.v1_hire_jobs_job_id_candidate_candidate_id_scorecards import get
from keka_hr_python_sdk import configuration, schemas, api_client

from .. import ApiTestMixin


class TestV1HireJobsJobIdCandidateCandidateIdScorecards(ApiTestMixin, unittest.TestCase):
    """
    V1HireJobsJobIdCandidateCandidateIdScorecards unit test stubs
        Get scorecard of a specified candidate for a job candidate
    """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    response_status = 200






if __name__ == '__main__':
    unittest.main()
