# coding: utf-8

# flake8: noqa

"""
    Requisition

    Here's our story,  It all began with the frustration of using software that sucks. Prior to starting Keka, our core team was a 100 person business that needed an easy to use software for managing employees. We looked everywhere and all we found were software that was lousy and hard to use. We felt SME businesses in India deserved something better. Something awesome actually!  Thus emerged Keka!

    The version of the OpenAPI document: v1
    Generated by: https://konfigthis.com
"""

__version__ = "v1"

# import ApiClient
from keka_hr_python_sdk.api_client import ApiClient

# import Configuration
from keka_hr_python_sdk.configuration import Configuration

# import exceptions
from keka_hr_python_sdk.exceptions import OpenApiException
from keka_hr_python_sdk.exceptions import ApiAttributeError
from keka_hr_python_sdk.exceptions import ApiTypeError
from keka_hr_python_sdk.exceptions import ApiValueError
from keka_hr_python_sdk.exceptions import ApiKeyError
from keka_hr_python_sdk.exceptions import ApiException

from keka_hr_python_sdk.client import KekaHr
