from keka_hr_python_sdk.paths.payroll_paygroups_pay_group_id_paycycles_pay_cycle_id_paybatches_pay_batch_id_payments.get import ApiForget
from keka_hr_python_sdk.paths.payroll_paygroups_pay_group_id_paycycles_pay_cycle_id_paybatches_pay_batch_id_payments.put import ApiForput


class PayrollPaygroupsPayGroupIdPaycyclesPayCycleIdPaybatchesPayBatchIdPayments(
    ApiForget,
    ApiForput,
):
    pass
