# coding: utf-8

"""
    Requisition

    Here's our story,  It all began with the frustration of using software that sucks. Prior to starting Keka, our core team was a 100 person business that needed an easy to use software for managing employees. We looked everywhere and all we found were software that was lousy and hard to use. We felt SME businesses in India deserved something better. Something awesome actually!  Thus emerged Keka!

    The version of the OpenAPI document: v1
    Generated by: https://konfigthis.com
"""

import unittest

import keka_hr_python_sdk
from keka_hr_python_sdk.model.remuneration_type import RemunerationType
from keka_hr_python_sdk import configuration


class TestRemunerationType(unittest.TestCase):
    """RemunerationType unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
