# coding: utf-8

"""
    Requisition

    Here's our story,  It all began with the frustration of using software that sucks. Prior to starting Keka, our core team was a 100 person business that needed an easy to use software for managing employees. We looked everywhere and all we found were software that was lousy and hard to use. We felt SME businesses in India deserved something better. Something awesome actually!  Thus emerged Keka!

    The version of the OpenAPI document: v1
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from keka_hr_python_sdk.pydantic.api_employee_lookup import APIEmployeeLookup
from keka_hr_python_sdk.pydantic.api_employee_salary_component import APIEmployeeSalaryComponent
from keka_hr_python_sdk.pydantic.remuneration_type import RemunerationType

class APIEmployeeSalary(BaseModel):
    id: typing.Optional[typing.Optional[str]] = Field(None, alias='id')

    employee: typing.Optional[APIEmployeeLookup] = Field(None, alias='employee')

    ctc: typing.Optional[typing.Union[int, float]] = Field(None, alias='ctc')

    gross: typing.Optional[typing.Union[int, float]] = Field(None, alias='gross')

    remuneration_type: typing.Optional[RemunerationType] = Field(None, alias='remunerationType')

    effective_from: typing.Optional[datetime] = Field(None, alias='effectiveFrom')

    earnings: typing.Optional[typing.Optional[typing.List[APIEmployeeSalaryComponent]]] = Field(None, alias='earnings')

    deductions: typing.Optional[typing.Optional[typing.List[APIEmployeeSalaryComponent]]] = Field(None, alias='deductions')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
