# coding: utf-8

"""
    Requisition

    Here's our story,  It all began with the frustration of using software that sucks. Prior to starting Keka, our core team was a 100 person business that needed an easy to use software for managing employees. We looked everywhere and all we found were software that was lousy and hard to use. We felt SME businesses in India deserved something better. Something awesome actually!  Thus emerged Keka!

    The version of the OpenAPI document: v1
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from keka_hr_python_sdk.pydantic.api_employee_lookup import APIEmployeeLookup
from keka_hr_python_sdk.pydantic.api_review_cycle_lookup import APIReviewCycleLookup
from keka_hr_python_sdk.pydantic.api_review_group_lookup import APIReviewGroupLookup
from keka_hr_python_sdk.pydantic.api_review_rating import APIReviewRating
from keka_hr_python_sdk.pydantic.review_status import ReviewStatus

class APIEmployeeReview(BaseModel):
    summary: typing.Optional[typing.Optional[str]] = Field(None, alias='summary')

    id: typing.Optional[typing.Optional[str]] = Field(None, alias='id')

    employee: typing.Optional[APIEmployeeLookup] = Field(None, alias='employee')

    review_group: typing.Optional[APIReviewGroupLookup] = Field(None, alias='reviewGroup')

    review_cycle: typing.Optional[APIReviewCycleLookup] = Field(None, alias='reviewCycle')

    ratings: typing.Optional[typing.Optional[typing.List[APIReviewRating]]] = Field(None, alias='ratings')

    status: typing.Optional[ReviewStatus] = Field(None, alias='status')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
