# coding: utf-8

"""
    Requisition

    Here's our story,  It all began with the frustration of using software that sucks. Prior to starting Keka, our core team was a 100 person business that needed an easy to use software for managing employees. We looked everywhere and all we found were software that was lousy and hard to use. We felt SME businesses in India deserved something better. Something awesome actually!  Thus emerged Keka!

    The version of the OpenAPI document: v1
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict


class ExperienceDTO(BaseModel):
    # Gets or sets the company name.
    company_name: typing.Optional[typing.Optional[str]] = Field(None, alias='companyName')

    # Gets or sets the designation.
    designation: typing.Optional[typing.Optional[str]] = Field(None, alias='designation')

    # Gets or sets a value indicating whether this instance is currently working.
    is_currently_working: typing.Optional[bool] = Field(None, alias='isCurrentlyWorking')

    # Gets or sets the date of joining.
    date_of_joining: typing.Optional[typing.Optional[str]] = Field(None, alias='dateOfJoining')

    # Gets or sets the date of relieving.
    date_of_relieving: typing.Optional[typing.Optional[str]] = Field(None, alias='dateOfRelieving')

    # Gets or sets the location.
    location: typing.Optional[typing.Optional[str]] = Field(None, alias='location')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
