# coding: utf-8

"""
    Requisition

    Here's our story,  It all began with the frustration of using software that sucks. Prior to starting Keka, our core team was a 100 person business that needed an easy to use software for managing employees. We looked everywhere and all we found were software that was lousy and hard to use. We felt SME businesses in India deserved something better. Something awesome actually!  Thus emerged Keka!

    The version of the OpenAPI document: v1
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from keka_hr_python_sdk.pydantic.address import Address
from keka_hr_python_sdk.pydantic.blood_group import BloodGroup
from keka_hr_python_sdk.pydantic.gender import Gender
from keka_hr_python_sdk.pydantic.marital_status import MaritalStatus
from keka_hr_python_sdk.pydantic.personal_details_update_request_custom_fields import PersonalDetailsUpdateRequestCustomFields
from keka_hr_python_sdk.pydantic.relation import Relation

class PersonalDetailsUpdateRequest(BaseModel):
    display_name: typing.Optional[typing.Optional[str]] = Field(None, alias='displayName')

    first_name: typing.Optional[typing.Optional[str]] = Field(None, alias='firstName')

    middle_name: typing.Optional[typing.Optional[str]] = Field(None, alias='middleName')

    last_name: typing.Optional[typing.Optional[str]] = Field(None, alias='lastName')

    gender: typing.Optional[Gender] = Field(None, alias='gender')

    date_of_birth: typing.Optional[typing.Optional[datetime]] = Field(None, alias='dateOfBirth')

    work_phone: typing.Optional[typing.Optional[str]] = Field(None, alias='workPhone')

    home_phone: typing.Optional[typing.Optional[str]] = Field(None, alias='homePhone')

    personal_email: typing.Optional[typing.Optional[str]] = Field(None, alias='personalEmail')

    skype_id: typing.Optional[typing.Optional[str]] = Field(None, alias='skypeId')

    marital_status: typing.Optional[MaritalStatus] = Field(None, alias='maritalStatus')

    marriage_date: typing.Optional[typing.Optional[datetime]] = Field(None, alias='marriageDate')

    relations: typing.Optional[typing.Optional[typing.List[Relation]]] = Field(None, alias='relations')

    blood_group: typing.Optional[BloodGroup] = Field(None, alias='bloodGroup')

    current_address: typing.Optional[Address] = Field(None, alias='currentAddress')

    permanent_address: typing.Optional[Address] = Field(None, alias='permanentAddress')

    professional_summary: typing.Optional[typing.Optional[str]] = Field(None, alias='professionalSummary')

    custom_fields: typing.Optional[PersonalDetailsUpdateRequestCustomFields] = Field(None, alias='customFields')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
