# coding: utf-8

"""
    Requisition

    Here's our story,  It all began with the frustration of using software that sucks. Prior to starting Keka, our core team was a 100 person business that needed an easy to use software for managing employees. We looked everywhere and all we found were software that was lousy and hard to use. We felt SME businesses in India deserved something better. Something awesome actually!  Thus emerged Keka!

    The version of the OpenAPI document: v1
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from keka_hr_python_sdk.pydantic.filtering_options import FilteringOptions
from keka_hr_python_sdk.pydantic.paging_options import PagingOptions
from keka_hr_python_sdk.pydantic.query_options_fields_to_return import QueryOptionsFieldsToReturn
from keka_hr_python_sdk.pydantic.query_options_searchable_options import QueryOptionsSearchableOptions
from keka_hr_python_sdk.pydantic.sorting_options import SortingOptions

class QueryOptions(BaseModel):
    paging_options: typing.Optional[PagingOptions] = Field(None, alias='pagingOptions')

    sorting_options: typing.Optional[SortingOptions] = Field(None, alias='sortingOptions')

    filter_options: typing.Optional[FilteringOptions] = Field(None, alias='filterOptions')

    searchable_options: typing.Optional[QueryOptionsSearchableOptions] = Field(None, alias='searchableOptions')

    fields_to_return: typing.Optional[QueryOptionsFieldsToReturn] = Field(None, alias='fieldsToReturn')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
