# coding: utf-8

"""
    Requisition

    Here's our story,  It all began with the frustration of using software that sucks. Prior to starting Keka, our core team was a 100 person business that needed an easy to use software for managing employees. We looked everywhere and all we found were software that was lousy and hard to use. We felt SME businesses in India deserved something better. Something awesome actually!  Thus emerged Keka!

    The version of the OpenAPI document: v1
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from keka_hr_python_sdk.type.api_employee_lookup import APIEmployeeLookup
from keka_hr_python_sdk.type.task_billing_type import TaskBillingType
from keka_hr_python_sdk.type.task_type import TaskType

class RequiredAPIProjectTask(TypedDict):
    pass

class OptionalAPIProjectTask(TypedDict, total=False):
    description: typing.Optional[str]

    id: typing.Optional[str]

    projectId: typing.Optional[str]

    name: typing.Optional[str]

    taskType: TaskType

    taskBillingType: TaskBillingType

    assignedTo: typing.Optional[typing.List[APIEmployeeLookup]]

    startDate: datetime

    endDate: datetime

    estimatedHours: typing.Optional[typing.Union[int, float]]

    identifier: typing.Optional[str]

class APIProjectTask(RequiredAPIProjectTask, OptionalAPIProjectTask):
    pass
