# coding: utf-8

"""
    Requisition

    Here's our story,  It all began with the frustration of using software that sucks. Prior to starting Keka, our core team was a 100 person business that needed an easy to use software for managing employees. We looked everywhere and all we found were software that was lousy and hard to use. We felt SME businesses in India deserved something better. Something awesome actually!  Thus emerged Keka!

    The version of the OpenAPI document: v1
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from keka_hr_python_sdk.type.api_base_goal import APIBaseGoal
from keka_hr_python_sdk.type.api_goal_tags import APIGoalTags
from keka_hr_python_sdk.type.goal_metric_type import GoalMetricType
from keka_hr_python_sdk.type.goal_status import GoalStatus
from keka_hr_python_sdk.type.goal_type import GoalType

class RequiredAPIGoal(TypedDict):
    pass

class OptionalAPIGoal(TypedDict, total=False):
    tags: typing.Optional[APIGoalTags]

    description: typing.Optional[str]

    id: typing.Optional[str]

    employeeId: typing.Optional[str]

    employeeNumber: typing.Optional[str]

    timeFrameId: typing.Optional[str]

    name: typing.Optional[str]

    startDate: datetime

    endDate: datetime

    initialValue: typing.Union[int, float]

    targetValue: typing.Union[int, float]

    currentValue: typing.Union[int, float]

    progress: typing.Union[int, float]

    metricType: GoalMetricType

    status: GoalStatus

    type: GoalType

    departmentId: typing.Optional[str]

    parentGoal: APIBaseGoal

    childGoals: typing.Optional[typing.List[APIBaseGoal]]

    isPrivate: bool

class APIGoal(RequiredAPIGoal, OptionalAPIGoal):
    pass
