# coding: utf-8

"""
    Requisition

    Here's our story,  It all began with the frustration of using software that sucks. Prior to starting Keka, our core team was a 100 person business that needed an easy to use software for managing employees. We looked everywhere and all we found were software that was lousy and hard to use. We felt SME businesses in India deserved something better. Something awesome actually!  Thus emerged Keka!

    The version of the OpenAPI document: v1
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from keka_hr_python_sdk.type.attendance_day_type import AttendanceDayType
from keka_hr_python_sdk.type.attendance_time_entry import AttendanceTimeEntry
from keka_hr_python_sdk.type.leave_day_status import LeaveDayStatus

class RequiredAttendanceSummary(TypedDict):
    pass

class OptionalAttendanceSummary(TypedDict, total=False):
    id: typing.Optional[str]

    employeeNumber: typing.Optional[str]

    employeeIdentifier: typing.Optional[str]

    attendanceDate: datetime

    dayType: AttendanceDayType

    leaveDayStatus: LeaveDayStatus

    shiftStartTime: datetime

    shiftEndTime: datetime

    shiftDuration: typing.Union[int, float]

    shiftBreakDuration: typing.Union[int, float]

    shiftEffectiveDuration: typing.Union[int, float]

    totalGrossHours: typing.Union[int, float]

    totalEffectiveHours: typing.Union[int, float]

    totalBreakDuration: typing.Union[int, float]

    totalEffectiveOvertimeDuration: typing.Union[int, float]

    totalGrossOvertimeDuration: typing.Union[int, float]

    firstInOfTheDay: AttendanceTimeEntry

    lastOutOfTheDay: AttendanceTimeEntry

class AttendanceSummary(RequiredAttendanceSummary, OptionalAttendanceSummary):
    pass
