# coding: utf-8

"""
    Requisition

    Here's our story,  It all began with the frustration of using software that sucks. Prior to starting Keka, our core team was a 100 person business that needed an easy to use software for managing employees. We looked everywhere and all we found were software that was lousy and hard to use. We felt SME businesses in India deserved something better. Something awesome actually!  Thus emerged Keka!

    The version of the OpenAPI document: v1
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredLeaveBalanceListItem(TypedDict):
    pass

class OptionalLeaveBalanceListItem(TypedDict, total=False):
    leaveTypeId: str

    leaveTypeName: typing.Optional[str]

    accruedAmount: typing.Union[int, float]

    consumedAmount: typing.Union[int, float]

    availableBalance: typing.Union[int, float]

    annualQuota: typing.Union[int, float]

class LeaveBalanceListItem(RequiredLeaveBalanceListItem, OptionalLeaveBalanceListItem):
    pass
