# coding: utf-8

"""
    Requisition

    Here's our story,  It all began with the frustration of using software that sucks. Prior to starting Keka, our core team was a 100 person business that needed an easy to use software for managing employees. We looked everywhere and all we found were software that was lousy and hard to use. We felt SME businesses in India deserved something better. Something awesome actually!  Thus emerged Keka!

    The version of the OpenAPI document: v1
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from keka_hr_python_sdk.type.error_detail import ErrorDetail

class RequiredOkErrorResponse(TypedDict):
    pass

class OptionalOkErrorResponse(TypedDict, total=False):
    # Gets or sets the HTTP status code of the response.
    status: int

    # Gets a value indicating whether the response operation succeeded (HTTP status code within the range of 200 to 299).
    succeeded: bool

    # Gets or sets the message associated with the response.
    message: typing.Optional[str]

    # Gets or sets the list of error details for individual fields.
    errors: typing.Optional[typing.List[ErrorDetail]]

    # Gets or sets the error code associated with the error.
    errorCode: typing.Optional[str]

class OkErrorResponse(RequiredOkErrorResponse, OptionalOkErrorResponse):
    pass
