# coding: utf-8

"""
    Requisition

    Here's our story,  It all began with the frustration of using software that sucks. Prior to starting Keka, our core team was a 100 person business that needed an easy to use software for managing employees. We looked everywhere and all we found were software that was lousy and hard to use. We felt SME businesses in India deserved something better. Something awesome actually!  Thus emerged Keka!

    The version of the OpenAPI document: v1
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from keka_hr_python_sdk.type.field_option_dto import FieldOptionDTO
from keka_hr_python_sdk.type.field_type import FieldType

class RequiredTalentPoolApplicationFieldsDTO(TypedDict):
    pass

class OptionalTalentPoolApplicationFieldsDTO(TypedDict, total=False):
    # Gets or sets the name of the field.
    fieldName: typing.Optional[str]

    # Gets or sets a value indicating whether this Keka.Hire.Core.Entities.Field is required.
    required: bool

    fieldType: FieldType

    # Gets or sets a value indicating whether this field is system generated.
    isSystemDefined: bool

    # Gets or sets the field options.
    fieldOptions: typing.Optional[typing.List[FieldOptionDTO]]

    # Gets or sets the identifier
    id: typing.Optional[str]

class TalentPoolApplicationFieldsDTO(RequiredTalentPoolApplicationFieldsDTO, OptionalTalentPoolApplicationFieldsDTO):
    pass
