# coding: utf-8

"""
    Requisition

    Here's our story,  It all began with the frustration of using software that sucks. Prior to starting Keka, our core team was a 100 person business that needed an easy to use software for managing employees. We looked everywhere and all we found were software that was lousy and hard to use. We felt SME businesses in India deserved something better. Something awesome actually!  Thus emerged Keka!

    The version of the OpenAPI document: v1
    Generated by: https://konfigthis.com
"""

from keka_hr_python_sdk.paths.hris_employees.post import CreateEmployeeRaw
from keka_hr_python_sdk.paths.hris_employees.get import GetAllRaw
from keka_hr_python_sdk.paths.hris_employees_updatefields.get import GetAllUpdateFieldsRaw
from keka_hr_python_sdk.paths.hris_employees_id.get import GetByIdRaw
from keka_hr_python_sdk.paths.hris_employees_id_jobdetails.put import UpdateJobDetailsRaw
from keka_hr_python_sdk.paths.hris_employees_id_personaldetails.put import UpdatePersonalDetailsRaw


class EmployeesApiRaw(
    CreateEmployeeRaw,
    GetAllRaw,
    GetAllUpdateFieldsRaw,
    GetByIdRaw,
    UpdateJobDetailsRaw,
    UpdatePersonalDetailsRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
