# coding: utf-8

"""
    Requisition

    Here's our story,  It all began with the frustration of using software that sucks. Prior to starting Keka, our core team was a 100 person business that needed an easy to use software for managing employees. We looked everywhere and all we found were software that was lousy and hard to use. We felt SME businesses in India deserved something better. Something awesome actually!  Thus emerged Keka!

    The version of the OpenAPI document: v1
    Generated by: https://konfigthis.com
"""

from keka_hr_python_sdk.paths.v1_hire_jobs_job_id_candidate_candidate_id_notes.post import AddCandidateNote
from keka_hr_python_sdk.paths.v1_hire_jobs.get import GetAllPublishedJobs
from keka_hr_python_sdk.paths.v1_hire_jobs_job_id_applicationfields.get import GetApplicationFields
from keka_hr_python_sdk.paths.v1_hire_jobs_job_id_candidate_candidate_id_interviews.get import GetCandidateInterviews
from keka_hr_python_sdk.paths.v1_hire_jobs_job_id_candidate_candidate_id_scorecards.get import GetCandidateScorecards
from keka_hr_python_sdk.paths.v1_hire_jobs_job_id_candidates.get import GetCandidates
from keka_hr_python_sdk.paths.v1_hire_jobs_job_id_candidate.post import PostCandidate
from keka_hr_python_sdk.paths.v1_hire_jobs_job_id_candidate_candidate_id.put import UpdateCandidate
from keka_hr_python_sdk.apis.tags.jobs_api_raw import JobsApiRaw


class JobsApi(
    AddCandidateNote,
    GetAllPublishedJobs,
    GetApplicationFields,
    GetCandidateInterviews,
    GetCandidateScorecards,
    GetCandidates,
    PostCandidate,
    UpdateCandidate,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: JobsApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = JobsApiRaw(api_client)
