# coding: utf-8

"""
    Requisition

    Here's our story,  It all began with the frustration of using software that sucks. Prior to starting Keka, our core team was a 100 person business that needed an easy to use software for managing employees. We looked everywhere and all we found were software that was lousy and hard to use. We felt SME businesses in India deserved something better. Something awesome actually!  Thus emerged Keka!

    The version of the OpenAPI document: v1
    Generated by: https://konfigthis.com
"""

from keka_hr_python_sdk.paths.v1_hire_jobs_job_id_candidate_candidate_id_notes.post import AddCandidateNoteRaw
from keka_hr_python_sdk.paths.v1_hire_jobs.get import GetAllPublishedJobsRaw
from keka_hr_python_sdk.paths.v1_hire_jobs_job_id_applicationfields.get import GetApplicationFieldsRaw
from keka_hr_python_sdk.paths.v1_hire_jobs_job_id_candidate_candidate_id_interviews.get import GetCandidateInterviewsRaw
from keka_hr_python_sdk.paths.v1_hire_jobs_job_id_candidate_candidate_id_scorecards.get import GetCandidateScorecardsRaw
from keka_hr_python_sdk.paths.v1_hire_jobs_job_id_candidates.get import GetCandidatesRaw
from keka_hr_python_sdk.paths.v1_hire_jobs_job_id_candidate.post import PostCandidateRaw
from keka_hr_python_sdk.paths.v1_hire_jobs_job_id_candidate_candidate_id.put import UpdateCandidateRaw


class JobsApiRaw(
    AddCandidateNoteRaw,
    GetAllPublishedJobsRaw,
    GetApplicationFieldsRaw,
    GetCandidateInterviewsRaw,
    GetCandidateScorecardsRaw,
    GetCandidatesRaw,
    PostCandidateRaw,
    UpdateCandidateRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
